{{ config(materialized='incremental', unique_key='GLOBAL_EVENT_ID', incremental_strategy='merge') }}

WITH GDELT_CLEAN_CTE AS (
    SELECT 
        * FROM {{ source('GDELT', 'GDELT_EVENT_DATABASE_1_0_RAW')}}
    WHERE EVENTCODE NOT IN ('--','---', 'X')
),

GDELT_EVENTS_CTE AS (
    SELECT 
    GLOBALEVENTID::BIGINT AS GLOBAL_EVENT_ID,
    TO_DATE(SQLDATE, 'YYYYMMDD') AS EVENT_DATE,
    ACTOR1CODE::VARCHAR AS ACTOR_1_CODE,
    ACTOR1NAME::VARCHAR AS ACTOR_1_NAME,
    ACTOR1COUNTRYCODE::VARCHAR AS ACTOR_1_COUNTRY_CODE,
    ACTOR1KNOWNGROUPCODE::VARCHAR AS ACTOR_1_KNOWNGROUP_CODE,
    ACTOR1RELIGION1CODE::VARCHAR AS ACTOR_1_RELIGION_1_CODE,
    ACTOR1RELIGION2CODE::VARCHAR AS ACTOR_1_RELIGION_2_CODE,
    ACTOR1TYPE1CODE::VARCHAR AS ACTOR_1_TYPE_1_CODE,
    ACTOR1TYPE2CODE::VARCHAR AS ACTOR_1_TYPE_2_CODE,
    ACTOR1TYPE3CODE::VARCHAR AS ACTOR_1_TYPE_3_CODE,
    ACTOR2CODE::VARCHAR AS ACTOR_2_CODE,
    ACTOR2NAME::VARCHAR AS ACTOR_2_NAME,
    ACTOR2COUNTRYCODE::VARCHAR AS ACTOR_2_COUNTRY_CODE,
    ACTOR2KNOWNGROUPCODE::VARCHAR AS ACTOR_2_KNOWNGROUP_CODE,
    ACTOR2RELIGION1CODE::VARCHAR AS ACTOR_2_RELIGION_1_CODE,
    ACTOR2RELIGION2CODE::VARCHAR AS ACTOR_2_RELIGION_2_CODE,
    ACTOR2TYPE1CODE::VARCHAR AS ACTOR_2_TYPE_1_CODE,
    ACTOR2TYPE2CODE::VARCHAR AS ACTOR_2_TYPE_2_CODE,
    ACTOR2TYPE3CODE::VARCHAR AS ACTOR_2_TYPE_3_CODE,
    ISROOTEVENT::INT AS IS_ROOT_EVENT,
    EVENTCODE::INT AS EVENT_CODE,
    EVENTBASECODE::INT AS EVENT_BASE_CODE,
    EVENTROOTCODE::INT AS EVENT_ROOT_CODE,
    QUADCLASS::INT,
    GOLDSTEINSCALE::FLOAT AS GOLDSTEIN_SCALE,
    NUMMENTIONS::INT AS NUM_MENTIONS,
    NUMSOURCES::INT AS NUM_SOURCES,
    NUMARTICLES::INT AS NUM_ARTICLES,
    AVGTONE::NUMBER(18,14) AS AVG_TONE,
    ACTIONGEO_TYPE::INT AS ACTION_GEO_TYPE,
    ACTIONGEO_FULLNAME::VARCHAR AS ACTION_GEO_FULL_NAME,
    ACTIONGEO_COUNTRYCODE::VARCHAR AS ACTION_GEO_COUNTRY_CODE,
    TO_DATE(DATEADDED,'YYYYMMDD') AS DATE_ADDED,
    SOURCEURL::VARCHAR AS SOURCE_URL
    FROM GDELT_CLEAN_CTE
)

SELECT * FROM GDELT_EVENTS_CTE